# Generated by Django 3.0.5 on 2020-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2000)),
                ('truth', models.CharField(max_length=50)),
                ('cube', models.CharField(max_length=50)),
                ('spam', models.CharField(max_length=50)),
                ('google_spam', models.FloatField()),
                ('google_not_spam', models.FloatField()),
                ('ibm', models.CharField(max_length=50)),
                ('ibm_spam', models.FloatField()),
                ('ibm_not_spam', models.FloatField()),
            ],
        ),
    ]
