# Generated by Django 3.0.5 on 2020-04-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='spam',
            new_name='google',
        ),
    ]
